INT-156: Added api region support
storyblok/storyblok-ruby pull request #25
Opened 2022-02-03 12:19 UTC by joaokamun

Added support to api_region parameter.

2022-02-07 19:36 UTC, romeucarvalho commented on lib/storyblok/client.rb
> +      end
I would like to suggest just a little reading improvement:
```
      protocol = "http#{configuration[:secure] ? 's' : ''}"

      if configuration[:api_url]
        "#{protocol}://#{configuration[:api_url]}/v#{configuration[:api_version]}"
      else
        region = configuration[:api_region] ? "-#{configuration[:api_region]}" : ""

        "#{protocol}://api#{region}.storyblok.com/v#{configuration[:api_version]}"
      end
```

2022-02-07 20:29 UTC, JosimarCamargo commented on lib/storyblok/client.rb
> +      api_url: false,
A suggestion to deal with that, would be get the api_region from the api_url sent. But a recent backend change where the space is created on the region to where this request is sent, so maybe this PR would be necessary, please correct if I'm wrong @joaokamun .

2022-02-07 20:31 UTC, JosimarCamargo requested changes
Maybe this PR would not be necessary anymore.

2022-02-07 20:45 UTC, JosimarCamargo reviewed
Updating the review status

2022-02-09 17:20 UTC, JosimarCamargo reviewed
**I recommend that we merge these changes only after our backend be totally prepared for the regions feature**

2022-02-09 17:24 UTC, joaokamun commented on lib/storyblok/client.rb
> +      end
Fixed on last commit.

2022-02-09 18:53 UTC, romeucarvalho approved these changes

2022-08-02 21:21 UTC, JosimarCamargo approved these changes

2022-08-02 21:22 UTC, merged